# Generated by Django 4.1.4 on 2023-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('DoctorID', models.CharField(max_length=255, null=True)),
                ('First_name', models.CharField(max_length=255, null=True)),
                ('Last_name', models.CharField(max_length=255, null=True)),
                ('Phone_Number1', models.CharField(max_length=255, null=True)),
                ('Address', models.TextField(null=True)),
                ('Email_Address', models.EmailField(max_length=255, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
                ('Medical_Field', models.CharField(max_length=255, null=True)),
                ('File_Diploma', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'doctor_a',
            },
        ),
        migrations.CreateModel(
            name='Doctor_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=50, null=True)),
                ('date_hour_shift_finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hospital_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'hospital_admin',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientֹName', models.CharField(max_length=20, null=True)),
                ('Email_Address', models.CharField(max_length=30, null=True)),
                ('matter', models.CharField(max_length=10, null=True)),
                ('doctorName', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='patient_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('patientID', models.CharField(max_length=255, null=True)),
                ('First_name', models.CharField(max_length=255, null=True)),
                ('Last_name', models.CharField(max_length=255, null=True)),
                ('Phone_Number', models.CharField(max_length=255, null=True)),
                ('Address', models.TextField(null=True)),
                ('Email_Address', models.EmailField(max_length=255, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_a',
            },
        ),
    ]
