# Generated by Django 4.1.4 on 2023-01-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'db_table': 'doctor_reply',
            },
        ),
        migrations.DeleteModel(
            name='Doctor_updates',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='patientֹName',
        ),
        migrations.AddField(
            model_name='messages',
            name='doctorID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='patientID',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='patientName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Email_Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='doctorName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='matter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor_reply',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.messages'),
        ),
    ]
