# Generated by Django 4.1.4 on 2023-01-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_reply_delete_doctor_updates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_shift_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_updates', to='core.doctor_a')),
            ],
            options={
                'db_table': 'doctor_shift_update',
            },
        ),
    ]
